apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-ccgv
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/dc-metro-map-ccgv@sha256:bba556b30a989beeb433650d93c7271be92dbbd7a29f47b3e397fd5e738baf3e
        name: my-nodejs
        resources: {}
status: {}
