apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-zwi0
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/devfile-sample-python-basic-zwi0@sha256:59976e68d1700a0902e4356a68e42d0fe875f850ddf344441b3ae1409b354c96
        name: my-python
        resources: {}
status: {}
